### ISSUE TITLE
Preview doesn't work

### ISSUE THREAD

**Issue by rahulnakarmi** [BramvdnHeuvel/Rickroll-Generator#4]
Tried different links and websites for the display picture but sadly it doesn't show up in the preview.
Also, thank you so much for making this and also adding the counter.
![Screenshot 2021-05-04 200732](https://user-images.githubusercontent.com/38591023/117018609-60ce0e00-ad14-11eb-9a62-3d1b01dc16ab.png)

**Comment by BramvdnHeuvel** [comment]
The website uses all metatags recommended by [Meta Tags](https://metatags.io/). I have updated them a while ago.

Let me know if you still experience this issue.
